FROM nimlang/nim AS builder

RUN git clone https://github.com/nim-lang/Nim.git -b version-1-6 --single-branch

WORKDIR /Nim

RUN apt update -y && apt install build-essential git wget -y

RUN ./build_all.sh

RUN ./koch docs --skipUserCfg --skipParentCfg --hints:off

FROM nginx
COPY --from=builder /Nim/web/upload/1.6.13 /usr/share/nginx/html
