FROM node:16-alpine3.17

RUN apk add git

RUN apk add --no-cache bash

USER node

WORKDIR /home/node

RUN git clone https://github.com/tamagui/tamagui.git

WORKDIR /home/node/tamagui

RUN yarn

RUN yarn workspace @tamagui/site ci:build

EXPOSE 3333

CMD [ "yarn workspace @tamagui/site next:start" ]
