FROM node:16-alpine3.17

RUN apk add git

RUN apk add --no-cache bash

USER node

WORKDIR /home/node

RUN git clone https://github.com/urbit/developers.urbit.org.git

WORKDIR /home/node/developers.urbit.org

RUN npm install

RUN npm i http-server

RUN npm run build

CMD [ "npm", "run", "start" ]
