FROM node:16-alpine3.17

RUN apk add git

RUN apk add --no-cache bash

USER node

WORKDIR /home/node

RUN git clone https://github.com/thisbeyond/solid-dnd-site.git

WORKDIR /home/node/solid-dnd-site

RUN npm install

RUN npm i http-server

RUN npm run build

CMD ["npx", "http-server", "dist" ]
